# Generated by Django 2.2.3 on 2021-09-20 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20210920_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 23, 41, 54, 245400, tzinfo=utc)),
        ),
    ]
